tab = int(input('Digite o numero que deseja saber a tabuada: '))
print('Tabuada do 0 ao 10')
print('-'*12)
print(' 0 X {} = {}'.format(tab, tab*0))
print(' 1 X {} = {}'.format(tab, tab*1))
print(' 2 X {} = {}'.format(tab, tab*2))
print(' 3 X {} = {}'.format(tab, tab*3))
print(' 4 X {} = {}'.format(tab, tab*4))
print(' 5 X {} = {}'.format(tab, tab*5))
print(' 6 X {} = {}'.format(tab, tab*6))
print(' 7 X {} = {}'.format(tab, tab*7))
print(' 8 X {} = {}'.format(tab, tab*8))
print(' 9 X {} = {}'.format(tab, tab*9))
print('10 X {} = {}'.format(tab, tab*10))
print('-'*12)
